version: '3.9'

services:
  redis:
    image: redis:6.0-alpine
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - local

networks:
  local:
    name: local
    driver: bridge